on: push
name: Deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Clean
      uses: heowc/action-hexo@main
      with:
        args: clean
    - name: Deploy
      uses: heowc/action-hexo@main
      env:
        EMAIL: enderavaitia@gmail.com
        NAME: EnderAvaritia
      with:
        args: deploy
